### ISSUE TITLE
Updating the Mermaid Worker

### ISSUE THREAD

**Issue by mhmadl** [Whoopsadaisy/yellow-mermaid#1]
Hi! I am glad that you created Mermaid for Yellow. Could you please update it to the new mermaid for latest version of Yellow? Billion thanks!

**Comment by Whoopsadaisy** [comment]
Updated to work with yellow 0.9.
Please check.

**Comment by mhmadl** [comment]
> Updated to work with yellow 0.9. Please check.

Thanks, Whoopsadaisy! Billion thanks!
